secrets:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:T2mxfqUcPC2JtmQHz4hRu6gcCtU=,iv:1qQmvLX2Xd2dmu8TWzf+vEvXC6MQ+oDCIBKJEJly8c0=,tag:8KRgDKTQ96o59M2qi6lS9Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pO6MwsLhI8Pa5ma52cYpZ76iaf9OgHxthPp6q4bmSgh3cre4DocN3g==,iv:o0EVikQrRtvdlmKnEOL6ewVWBhZhv01Vl4FAGvb25GQ=,tag:9Z9OmxcP4Wrs0bbsficd0Q==,type:str]
    API_KEY: ENC[AES256_GCM,data:EOcu5BV3Xa4t8kyRwAvr3Ro9Olezb00LS6bFel4yrwY=,iv:JG1UUXJ9MRQRYpifKAIEZ+HRibx4d/8den5qdb4SxVE=,tag:jrB4dBvmBXSB8YOO3iEEdQ==,type:str]
    API_KEY_NAME: ENC[AES256_GCM,data:NBPUEqzjLw==,iv:VVyA3fjeZdhvFs/cp0iFue4ACuJYV7yT2SkdL+fHCZI=,tag:NRYC4AWaD57bIhCdutiuHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-05-25T07:10:49Z'
    mac: ENC[AES256_GCM,data:b1m1r145ZnKG9QjjPKJOdwF8aUzcGdfT6FX8fcSpK0HugsCQiwNhtNYj38CoIaYwePPBpGUYBXwO1IDm3EhfaWX4jYWF4OYasMw0hOeKqjyEOWDjeeTuVyCi8+9Grfak8QBUQgVZDbTzOnPFhwanshyysxm0G7ld40qDazznrWU=,iv:BBRia9rgoXQTTXCuiobF+64s5L9OqpwSJ8/Hf/8OZPg=,tag:oX0keTAlP2DriXTNX4PCQg==,type:str]
    pgp:
    -   created_at: '2020-11-30T07:30:56Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hH4DTbnv4i6E7RESAgMEVZKJtSMyrrI0jJ8PyVbnMOMxDvqrGfqPFGdMLJDG0Ss3
            bgNNi2f4N0oARco75cFbDAZb4Z5pzLHsP8sLnjJjlzCE8HcMk2py/76y0ggsIL/N
            s8fUgalY795iPIMji5pvfNrk9eDFeVN0YlinEmMrDKPSXgEKlfDVWwEuJofVjpYl
            0zOy0CnggqM05PZMIuf4EqqXUrUbz082+Z7NvupDEvnqEOVIvJeKG6aEziaxFMyb
            BRrtzDQXoFXxRCaZXnwNdNqo6PK+07ApaF1U5VjqGHM=
            =LsSl
            -----END PGP MESSAGE-----
        fp: 3CAFE454CD9F1977A155A2E715A79E9BF178C897
    unencrypted_suffix: _unencrypted
    version: '1.18'
