version: '3.1'
services:
  lead-scoring-api:
    build:
      dockerfile: docker/dev/Dockerfile
      context: ..
    env_file:
    - ../.env
    environment:
      - NO_WORKERS=1
    ports:
    - 8000:8000

